---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

## Introduction

This is the research repository for the evaluation of the MedStar-Klarus Mobile Health Paramedic (MHP) program. If this is your first visit to the page, you may want to start by clicking on the "Dashboard" link below.

## Table of Contents

1. [Dashboard](insert rawgit link here). Click on the analysis dashboard link for an overview of all study results in a dashboard format.

2. [Study objectives](#objectives)

3. [Links to data cleaning and analysis codes](#codes). You can find the codes used to clean our data and perform statistical analysis in the folders above. Additionally, you can use the links provided in this section.

4. [Manuscript information](). This link is not yet active.

<H2 id = "objectives">Study objectives</H2>

Currently, our primary interest is in understanding the factors associated with transport to a hospital when the patient called 911.

<H2 id = "codes">Data cleaning and analysis codes</H2>

For more information about our analysis process and results, please click in the individual code file of interest below:

[Code used for importing data into R](insert relative link here)

[Code used for data managemet]()

