---
title: "Import Data"
date: "Created: 2017-05-17 <br> Updated: `r Sys.Date()`"
output: github_document
---

```{r load_packages, message=FALSE}
# Load packages
library(tidyverse)
library(readxl)
library(feather)

# devtools::install_github("brad-cannell/my_functions")
library(myFunctions)
```

### Klarus patient list

```{r}
col_names <- c(
  "id", "gender", "zip", "soc", "start_date", "end_date", "primary_diagnosis", "secondary_diagnosis"
)

klarus <- read_excel(path = "../data/klarus_patient_list.xlsx", 
                     sheet = "klarus_patient_list",
                     col_names = col_names,
                     skip = 1)

about_data(klarus) # 2,524 observations and 8 variables
```

```{r}
write_feather(klarus, path = "../data/klarus.feather")
```

### MedStar patient list

```{r}
medstar <- read_excel(path = "../data/medstar_patient_list.xlsx", 
                     sheet = "medstar_patient_list",
                     col_names = c("id", "enrollment_date", "graduation_date", "death_date"),
                     skip = 1)

medstar$death_date <- as.POSIXct(medstar$death_date, format = "%m/%d/%Y")

about_data(medstar) # 627 observations and 4 variables
```

```{r}
write_feather(medstar, path = "../data/medstar.feather")
```

### Patient 911 calls

```{r}
col_names <- c(
  "id", "enrollment_id", "age", "encounter_date", "encounter_type", "determinant", "call_priority",
  "response_number", "incident_number", "ems_encounter_outcome", "transported", "mhp_responded", "mhp_on_scene",
  "vehicle_unit", "mhp_no_os_preventable", "no_ccp_available", "requested_transport", "client_other_address",
  "crew_trans_prior_ccp", "ccp_consult_prior_trans", "mhp_one", "mhp_two", "receiving_facility", 
  "encounter_notes", "comm_review_outcome"
)

calls <- read_excel(path = "../data/patient_911_calls.xlsx", 
                     sheet = "patient_911_calls",
                     col_names = col_names,
                     skip = 1)

about_data(calls) # 1,217 observations and 25 variables
```

```{r}
write_feather(calls, path = "../data/calls.feather")
```

-------------------------------------------------------------------------------

&nbsp;

#### Session Info:

```{r session_info, echo=FALSE}
sessionInfo()
```
